version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${process.env.NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_GOOGLE_CLIENT_ID=${process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID}
      - NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=${process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}
      - NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET=${process.env.NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET}

    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev