version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3001:3000"
    env_file:
      - .env.production
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - prisma-network